### ISSUE TITLE
Stack traces in Docker

### ISSUE THREAD

**Issue by AxelJunker** [dtolnay/anyhow#223]
Not sure if this is the right place to ask, but I will give it a go and maybe you can point me in the right direction.

I'm using `anyhow = { version = "1.0.53", features = ["backtrace"] }` and when running with `RUST_BACKTRACE=1 cargo run` I get nice stack traces pointing me to where the error originated from:

```
...
 6: my_project::my_function::{{closure}}
             at ./src/main.rs:84:16
...
```

However, when running in Docker I get a different (useless) stack trace:

```
Stack backtrace:
   0: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   1: tokio::park::thread::CachedParkThread::block_on
   2: tokio::runtime::thread_pool::ThreadPool::block_on
   3: tokio::runtime::Runtime::block_on
   4: my_project::main
   5: std::sys_common::backtrace::__rust_begin_short_backtrace
   6: std::rt::lang_start::{{closure}}
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406:40
      std::panicking::try
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal::{{closure}}
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128:48
      std::panicking::try::do_call
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:406:40
      std::panicking::try
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panicking.rs:370:19
      std::panic::catch_unwind
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/panic.rs:133:14
      std::rt::lang_start_internal
             at ./rustc/02072b482a8b5357f7fb5e5637444ae30e423c40/library/std/src/rt.rs:128:20
   8: main
   9: __libc_start_main
  10: _start
```

If I put a regular `panic!("panik")` anywhere in my code, I get the line number of the panic:

```
thread 'main' panicked at 'panik', src/main.rs:82:5
...
```

Any ideas on how to get better stack traces with line numbers in Docker?

**Comment by AxelJunker** [comment]
Got an answer here https://github.com/rust-lang/backtrace-rs/issues/461#issuecomment-1037228856
